name: "Setup and install"
description: "Common setup steps for Actions"

inputs:
  node-version:
    description: Version of Node to use
    default: 20.x

  pnpm-version:
    description: Version of pnpm to use
    default: 8.x

runs:
  using: composite
  steps:
    - name: 🏗 Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: 🏗 Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: 📦 Install dependencies
      run: pnpm install
      shell: bash
