name: Storybook Deploy

on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  FORCE_COLOR: 3

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Copy env
        shell: bash
        run: cp .env.example .env

      #👇 Add Storybook build and deploy to GitHub Pages as a step in the workflow
      - name: Deploy Storybook
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: pnpm install # default: npm ci
          build_command: pnpm storybook:build # default: npm run build-storybook
          path: storybook-static # default: dist/storybook
          # Set to false if the code is already checked out
          checkout: false # default: true
